# Site wide configuration

title:            nono.my.id
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Nono Heryana
  avatar: avatar.png
  bio: "Part time hard worker, full time dreamer."
  email: nonoheryana@gmail.com
  disqus-shortname: nonohry
  twitter: ryujiazka #username
  facebook: 
  google: 
    plus: 
    scholar: https://scholar.google.co.id/citations?user=OkLdAMQAAAAJ&hl=id
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: nonohry
  stackoverflow: #123456/username
  linkedin: nonohry
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
