# Core Jekyll Configuration
locale                : 'en'
timezone              : 'Asia/Jakarta'
# source              : 'nono'
destination           : 'html'
url                   : 'https://nono.my.id'
enforce_ssl           : 'nono.my.id'
permalink             : '/articles/:title'
include               : ['_pages']
plugins               : []

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# Progressive Web App Settings
pwa_title             : 'Nono'
pwa_themecolor        : '#1e88e5'
pwa_backgroundcolor   : '#1e88e5'

serviceworker         : true
#google_analytics      : 'UA-xxx'
disqus_name           : 'nonohry'

# Custom Jekyll Configuration
title                 : 'Nono Heryana'
tagline               : 'Hacker, Maker, Tinkerer, Learner'
description           : 'The personal website of Martin Groeneveld'
author                : 'Nono Heryana'
email                 : 'nonoheryana@gmail.com'

phone                 : '+62816795221'
address               : 'Karawang<br>Jawa Barat<br>Indonesia'
legal                 : '<a href="/terms">Terms</a> &bull; <a href="/privacy">Privacy</a>'
